
import React, { useState, useEffect } from 'react';
import { AdCopySet } from '../types';

interface RemixModalProps {
    isOpen: boolean;
    onClose: () => void;
    copySets: AdCopySet[];
    onConfirm: (selectedSet: AdCopySet) => void;
}

export const RemixModal: React.FC<RemixModalProps> = ({ isOpen, onClose, copySets, onConfirm }) => {
    const [selectedIdx, setSelectedIdx] = useState<number>(0);
    const [editedSets, setEditedSets] = useState<AdCopySet[]>([]);

    useEffect(() => {
        if (copySets.length > 0) {
            setEditedSets(copySets);
            setSelectedIdx(0);
        }
    }, [copySets]);

    if (!isOpen) return null;

    const currentSet = editedSets[selectedIdx];

    const handleEdit = (field: keyof AdCopySet, value: string) => {
        const newSets = [...editedSets];
        newSets[selectedIdx] = { ...newSets[selectedIdx], [field]: value };
        setEditedSets(newSets);
    };

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-md p-4 animate-in fade-in duration-200">
            <div className="bg-[#0F1014] border border-[#2A2D36] rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh] animate-in zoom-in-95 duration-200">

                {/* Header */}
                <div className="p-6 border-b border-[#2A2D36] flex justify-between items-center bg-[#0F1014]">
                    <div>
                        <h2 className="text-xl font-bold text-white tracking-tight">Review & Remix</h2>
                        <p className="text-sm text-gray-500">Select a new angle generated by AI.</p>
                    </div>
                    <button onClick={onClose} className="text-gray-500 hover:text-white transition-colors">
                        <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>
                    </button>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-6 flex flex-col gap-6 custom-scrollbar bg-[#09090b]">

                    {/* Tabs */}
                    <div className="flex gap-2 bg-[#15171B] p-1.5 rounded-xl border border-[#2A2D36]">
                        {editedSets.map((_, idx) => (
                            <button
                                key={idx}
                                onClick={() => setSelectedIdx(idx)}
                                className={`flex-1 py-2.5 rounded-lg text-sm font-semibold transition-all duration-200 ${selectedIdx === idx
                                        ? 'bg-[#2A2D36] text-white shadow-md'
                                        : 'text-gray-500 hover:text-gray-300 hover:bg-[#1F2229]'
                                    }`}
                            >
                                Concept {idx + 1}
                            </button>
                        ))}
                    </div>

                    {/* Form */}
                    {currentSet && (
                        <div className="space-y-5 bg-[#15171B] p-6 rounded-2xl border border-[#2A2D36]">
                            <div>
                                <label className="block text-[11px] text-gray-400 mb-2 font-semibold uppercase tracking-wider">Headline</label>
                                <input
                                    type="text"
                                    value={currentSet.headline}
                                    onChange={(e) => handleEdit('headline', e.target.value)}
                                    className="w-full bg-[#0F1014] border border-[#2A2D36] rounded-xl px-4 py-3 text-white focus:ring-1 focus:ring-violet-500/50 focus:border-violet-500/50 outline-none transition-all"
                                />
                            </div>

                            <div>
                                <label className="block text-[11px] text-gray-400 mb-2 font-semibold uppercase tracking-wider">Sub-Headline</label>
                                <textarea
                                    value={currentSet.subHeadline}
                                    onChange={(e) => handleEdit('subHeadline', e.target.value)}
                                    className="w-full bg-[#0F1014] border border-[#2A2D36] rounded-xl px-4 py-3 text-white focus:ring-1 focus:ring-violet-500/50 focus:border-violet-500/50 outline-none min-h-[80px] transition-all resize-none"
                                />
                            </div>

                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-[11px] text-gray-400 mb-2 font-semibold uppercase tracking-wider">CTA Button</label>
                                    <input
                                        type="text"
                                        value={currentSet.ctaText}
                                        onChange={(e) => handleEdit('ctaText', e.target.value)}
                                        className="w-full bg-[#0F1014] border border-[#2A2D36] rounded-xl px-4 py-3 text-white focus:ring-1 focus:ring-violet-500/50 focus:border-violet-500/50 outline-none transition-all"
                                    />
                                </div>
                                <div>
                                    <label className="block text-[11px] text-gray-400 mb-2 font-semibold uppercase tracking-wider">Scene Note</label>
                                    <input
                                        type="text"
                                        value={currentSet.sceneSuggestion}
                                        onChange={(e) => handleEdit('sceneSuggestion', e.target.value)}
                                        className="w-full bg-[#0F1014] border border-[#2A2D36] rounded-xl px-4 py-3 text-gray-300 focus:ring-1 focus:ring-violet-500/50 focus:border-violet-500/50 outline-none italic transition-all"
                                    />
                                </div>
                            </div>
                        </div>
                    )}

                </div>

                {/* Footer */}
                <div className="p-6 border-t border-[#2A2D36] bg-[#0F1014] flex justify-end gap-3">
                    <button
                        onClick={onClose}
                        className="px-5 py-3 rounded-xl text-gray-400 font-medium hover:bg-[#1F2229] transition-colors text-sm"
                    >
                        Cancel
                    </button>
                    <button
                        onClick={() => onConfirm(currentSet)}
                        className="px-8 py-3 rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 hover:from-violet-500 hover:to-fuchsia-500 text-white font-bold shadow-lg shadow-violet-500/20 transition-all transform active:scale-95 text-sm"
                    >
                        Generate New Batch
                    </button>
                </div>
            </div>
        </div>
    );
};
